### ISSUE TITLE
MS VisualStudio 14 Support

### ISSUE THREAD

**Issue by Johanneslueke** [SuperV1234/vrm_pp#1]
Hi....
single short question, actually related to your ecst: Does your vrm_pp and also vrm_core support in anyway VS14? I just tried but it refuses to work because the used compiler intrinsic's are not supported. Best example the PP argument "always_inline" ...simply does not exist. The holy gcc obviously does support it since the 90th as a compiler extension. 
Or did i just have not read your docs properly, i hope so because it implies i'm just to god damn stupid to read, if not it means i have to find a way around this issue.

**Comment by vittorioromeo** [comment]
Hey, sorry for the issue. I do not officially support MSVC - I only test my code on **g++** and **clang++**.

If you manage to fix the issues on MSVC, feel free to send a PR and I'll accept it. Otherwise, you may trying using MinGW if applicable *(which is what I use to compile my projects on Windows)*.

**Comment by Johanneslueke** [comment]
Yeah thought so ... Anyway Thanks alot for the answer. If a find the time I'll give it a try to add MSVC support and send you a PR... :smiley:
